name: Update badges

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  schedule:
    - cron: "0 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest

    steps:
      - name: Badges - Readme
        uses: atmarker/atmarker@main
        with:       
          CREDLY_USER: atmarker
